/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

import andorra from '../maps/json/andorra.json';
import angola from '../maps/json/angola.json';
import argentina from '../maps/json/argentina.json';
import armenia from '../maps/json/armenia.json';
import australia from '../maps/json/australia.json';
import austria from '../maps/json/austria.json';
import azerbaijan from '../maps/json/azerbaijan.json';
import bahamas from '../maps/json/bahamas.json';
import bahrain from '../maps/json/bahrain.json';
import bangladesh from '../maps/json/bangladesh.json';
import belarus from '../maps/json/belarus.json';
import belgium from '../maps/json/belgium.json';
import bhutan from '../maps/json/bhutan.json';
import bolivia from '../maps/json/bolivia.json';
import bosniaHerzegovina2 from '../maps/json/bosnia-herzegovina-2.json';
import bosniaHerzegovina from '../maps/json/bosnia-herzegovina.json';
import botswana from '../maps/json/botswana.json';
import brazil from '../maps/json/brazil.json';
import bruneiDarussalam from '../maps/json/brunei-darussalam.json';
import bulgaria from '../maps/json/bulgaria.json';
import burkinaFaso from '../maps/json/burkina-faso.json';
import burundi from '../maps/json/burundi.json';
import cambodia from '../maps/json/cambodia.json';
import cameroon from '../maps/json/cameroon.json';
import canada from '../maps/json/canada.json';
import capeVerde from '../maps/json/cape-verde.json';
import centralAfricanRepublic from '../maps/json/central-african-republic.json';
import chad from '../maps/json/chad.json';
import chile2 from '../maps/json/chile-2.json';
import chile from '../maps/json/chile.json';
import china from '../maps/json/china.json';
import colombia from '../maps/json/colombia.json';
import congoDr from '../maps/json/congo-dr.json';
import congo from '../maps/json/congo.json';
import costaRica from '../maps/json/costa-rica.json';
import croatia from '../maps/json/croatia.json';
import cuba from '../maps/json/cuba.json';
import cyprus from '../maps/json/cyprus.json';
import czechRepublic from '../maps/json/czech-republic.json';
import denmark from '../maps/json/denmark.json';
import djibouti from '../maps/json/djibouti.json';
import dominicanRepublic from '../maps/json/dominican-republic.json';
import ecuador from '../maps/json/ecuador.json';
import egypt from '../maps/json/egypt.json';
import elSalvador from '../maps/json/el-salvador.json';
import empty from '../maps/json/empty.json';
import estonia from '../maps/json/estonia.json';
import ethiopia from '../maps/json/ethiopia.json';
import faroeislands from '../maps/json/faroeIslands.json';
import finland from '../maps/json/finland.json';
import franceDepartments from '../maps/json/france-departments.json';
import franceNew from '../maps/json/france-new.json';
import france from '../maps/json/france.json';
import georgia from '../maps/json/georgia.json';
import germany from '../maps/json/germany.json';
import greece from '../maps/json/greece.json';
import guatemala from '../maps/json/guatemala.json';
import guinea from '../maps/json/guinea.json';
import haiti from '../maps/json/haiti.json';
import honduras from '../maps/json/honduras.json';
import hongKong from '../maps/json/hong-kong.json';
import hungary from '../maps/json/hungary.json';
import iceland from '../maps/json/iceland.json';
import india from '../maps/json/india.json';
import indonesia from '../maps/json/indonesia.json';
import iran from '../maps/json/iran.json';
import iraq from '../maps/json/iraq.json';
import ireland from '../maps/json/ireland.json';
import israel from '../maps/json/israel.json';
import italy from '../maps/json/italy.json';
import jamaica from '../maps/json/jamaica.json';
import japan from '../maps/json/japan.json';
import kazakhstan from '../maps/json/kazakhstan.json';
import kenya from '../maps/json/kenya.json';
import kosovo from '../maps/json/kosovo.json';
import kyrgyzstan from '../maps/json/kyrgyzstan.json';
import laos from '../maps/json/laos.json';
import latvia from '../maps/json/latvia.json';
import liechtenstein from '../maps/json/liechtenstein.json';
import lithuania from '../maps/json/lithuania.json';
import luxembourg from '../maps/json/luxembourg.json';
import macedonia from '../maps/json/macedonia.json';
import malaysia from '../maps/json/malaysia.json';
import mali from '../maps/json/mali.json';
import malta from '../maps/json/malta.json';
import mexico from '../maps/json/mexico.json';
import moldova from '../maps/json/moldova.json';
import montenegro from '../maps/json/montenegro.json';
import morocco from '../maps/json/morocco.json';
import myanmar from '../maps/json/myanmar.json';
import nepal from '../maps/json/nepal.json';
import netherlands from '../maps/json/netherlands.json';
import newZealand2 from '../maps/json/new-zealand-2.json';
import newZealand from '../maps/json/new-zealand.json';
import nicaragua from '../maps/json/nicaragua.json';
import nigeria from '../maps/json/nigeria.json';
import norway from '../maps/json/norway.json';
import oman from '../maps/json/oman.json';
import pakistan from '../maps/json/pakistan.json';
import palestine from '../maps/json/palestine.json';
import panama from '../maps/json/panama.json';
import paraguay from '../maps/json/paraguay.json';
import philippines from '../maps/json/philippines.json';
import poland from '../maps/json/poland.json';
import portugalRegions from '../maps/json/portugal-regions.json';
import portugal from '../maps/json/portugal.json';
import qatar from '../maps/json/qatar.json';
import romania from '../maps/json/romania.json';
import russia from '../maps/json/russia.json';
import rwanda from '../maps/json/rwanda.json';
import sanMarino from '../maps/json/san-marino.json';
import saudiArabia from '../maps/json/saudi-arabia.json';
import serbiaWithoutKosovo from '../maps/json/serbia-without-kosovo.json';
import serbia from '../maps/json/serbia.json';
import sierraLeone from '../maps/json/sierra-leone.json';
import singapore from '../maps/json/singapore.json';
import slovakia from '../maps/json/slovakia.json';
import slovenia from '../maps/json/slovenia.json';
import southAfrica2 from '../maps/json/south-africa-2.json';
import southAfrica from '../maps/json/south-africa.json';
import southKorea from '../maps/json/south-korea.json';
import spainProvinces from '../maps/json/spain-provinces.json';
import spain from '../maps/json/spain.json';
import sriLanka from '../maps/json/sri-lanka.json';
import sweden from '../maps/json/sweden.json';
import switzerland from '../maps/json/switzerland.json';
import syria from '../maps/json/syria.json';
import taiwan from '../maps/json/taiwan.json';
import tajikistan from '../maps/json/tajikistan.json';
import thailand from '../maps/json/thailand.json';
import turkey from '../maps/json/turkey.json';
import uganda from '../maps/json/uganda.json';
import ukraine from '../maps/json/ukraine.json';
import unitedArabEmirates from '../maps/json/united-arab-emirates.json';
import unitedKingdomCounties from '../maps/json/united-kingdom-counties.json';
import unitedKingdom from '../maps/json/united-kingdom.json';
import uruguay from '../maps/json/uruguay.json';
import usaAk from '../maps/json/usa-ak.json';
import usaAl from '../maps/json/usa-al.json';
import usaAr from '../maps/json/usa-ar.json';
import usaAz from '../maps/json/usa-az.json';
import usaCa from '../maps/json/usa-ca.json';
import usaCo from '../maps/json/usa-co.json';
import usaCt from '../maps/json/usa-ct.json';
import usaDe from '../maps/json/usa-de.json';
import usaFl from '../maps/json/usa-fl.json';
import usaGa from '../maps/json/usa-ga.json';
import usaHi from '../maps/json/usa-hi.json';
import usaIa from '../maps/json/usa-ia.json';
import usaId from '../maps/json/usa-id.json';
import usaIl from '../maps/json/usa-il.json';
import usaIn from '../maps/json/usa-in.json';
import usaKs from '../maps/json/usa-ks.json';
import usaKy from '../maps/json/usa-ky.json';
import usaLa from '../maps/json/usa-la.json';
import usaMa from '../maps/json/usa-ma.json';
import usaMd from '../maps/json/usa-md.json';
import usaMe from '../maps/json/usa-me.json';
import usaMi from '../maps/json/usa-mi.json';
import usaMn from '../maps/json/usa-mn.json';
import usaMo from '../maps/json/usa-mo.json';
import usaMs from '../maps/json/usa-ms.json';
import usaMt from '../maps/json/usa-mt.json';
import usaNc from '../maps/json/usa-nc.json';
import usaNd from '../maps/json/usa-nd.json';
import usaNe from '../maps/json/usa-ne.json';
import usaNh from '../maps/json/usa-nh.json';
import usaNj from '../maps/json/usa-nj.json';
import usaNm from '../maps/json/usa-nm.json';
import usaNotCalibrated from '../maps/json/usa-not-calibrated.json';
import usaNv from '../maps/json/usa-nv.json';
import usaNy from '../maps/json/usa-ny.json';
import usaOh from '../maps/json/usa-oh.json';
import usaOk from '../maps/json/usa-ok.json';
import usaOr from '../maps/json/usa-or.json';
import usaPa from '../maps/json/usa-pa.json';
import usaRi from '../maps/json/usa-ri.json';
import usaSc from '../maps/json/usa-sc.json';
import usaSd from '../maps/json/usa-sd.json';
import usaTn from '../maps/json/usa-tn.json';
import usaTx from '../maps/json/usa-tx.json';
import usaUt from '../maps/json/usa-ut.json';
import usaVa from '../maps/json/usa-va.json';
import usaVt from '../maps/json/usa-vt.json';
import usaWa from '../maps/json/usa-wa.json';
import usaWdc from '../maps/json/usa-wdc.json';
import usaWi from '../maps/json/usa-wi.json';
import usaWithAkHi from '../maps/json/usa-with-AK-HI.json';
import usaWv from '../maps/json/usa-wv.json';
import usaWy from '../maps/json/usa-wy.json';
import usa from '../maps/json/usa.json';
import uzbekistan from '../maps/json/uzbekistan.json';
import venezuela from '../maps/json/venezuela.json';
import vietnamWithIslands from '../maps/json/vietnam-with-islands.json';
import vietnam from '../maps/json/vietnam.json';
import worldLowRes from '../maps/json/world-low-res.json';
import world from '../maps/json/world.json';

export {
  andorra,
  angola,
  argentina,
  armenia,
  australia,
  austria,
  azerbaijan,
  bahamas,
  bahrain,
  bangladesh,
  belarus,
  belgium,
  bhutan,
  bolivia,
  bosniaHerzegovina2,
  bosniaHerzegovina,
  botswana,
  brazil,
  bruneiDarussalam,
  bulgaria,
  burkinaFaso,
  burundi,
  cambodia,
  cameroon,
  canada,
  capeVerde,
  centralAfricanRepublic,
  chad,
  chile2,
  chile,
  china,
  colombia,
  congoDr,
  congo,
  costaRica,
  croatia,
  cuba,
  cyprus,
  czechRepublic,
  denmark,
  djibouti,
  dominicanRepublic,
  ecuador,
  egypt,
  elSalvador,
  empty,
  estonia,
  ethiopia,
  faroeislands,
  finland,
  franceDepartments,
  franceNew,
  france,
  georgia,
  germany,
  greece,
  guatemala,
  guinea,
  haiti,
  honduras,
  hongKong,
  hungary,
  iceland,
  india,
  indonesia,
  iran,
  iraq,
  ireland,
  israel,
  italy,
  jamaica,
  japan,
  kazakhstan,
  kenya,
  kosovo,
  kyrgyzstan,
  laos,
  latvia,
  liechtenstein,
  lithuania,
  luxembourg,
  macedonia,
  malaysia,
  mali,
  malta,
  mexico,
  moldova,
  montenegro,
  morocco,
  myanmar,
  nepal,
  netherlands,
  newZealand2,
  newZealand,
  nicaragua,
  nigeria,
  norway,
  oman,
  pakistan,
  palestine,
  panama,
  paraguay,
  philippines,
  poland,
  portugalRegions,
  portugal,
  qatar,
  romania,
  russia,
  rwanda,
  sanMarino,
  saudiArabia,
  serbiaWithoutKosovo,
  serbia,
  sierraLeone,
  singapore,
  slovakia,
  slovenia,
  southAfrica2,
  southAfrica,
  southKorea,
  spainProvinces,
  spain,
  sriLanka,
  sweden,
  switzerland,
  syria,
  taiwan,
  tajikistan,
  thailand,
  turkey,
  uganda,
  ukraine,
  unitedArabEmirates,
  unitedKingdomCounties,
  unitedKingdom,
  uruguay,
  usaAk,
  usaAl,
  usaAr,
  usaAz,
  usaCa,
  usaCo,
  usaCt,
  usaDe,
  usaFl,
  usaGa,
  usaHi,
  usaIa,
  usaId,
  usaIl,
  usaIn,
  usaKs,
  usaKy,
  usaLa,
  usaMa,
  usaMd,
  usaMe,
  usaMi,
  usaMn,
  usaMo,
  usaMs,
  usaMt,
  usaNc,
  usaNd,
  usaNe,
  usaNh,
  usaNj,
  usaNm,
  usaNotCalibrated,
  usaNv,
  usaNy,
  usaOh,
  usaOk,
  usaOr,
  usaPa,
  usaRi,
  usaSc,
  usaSd,
  usaTn,
  usaTx,
  usaUt,
  usaVa,
  usaVt,
  usaWa,
  usaWdc,
  usaWi,
  usaWithAkHi,
  usaWv,
  usaWy,
  usa,
  uzbekistan,
  venezuela,
  vietnamWithIslands,
  vietnam,
  worldLowRes,
  world,
};
