name: Pull Request CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  deployDraftOnAnyPullRequest:
    name: Deploy draft to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci

      - name: Install docs dependencies
        run: npm run docs:install

      - name: Build docs
        run: npm run docs:build

      - name: Deploy draft to Netlify
        uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: "./docs/public"
          draft: true
          comment-on-pull-request: true
