const fs = require('fs');
const rimraf = require('rimraf');
const svgson = require('svgson');

const { asyncForEach, capitalize, stringify } = require('../utils');

const SVG_MAP_FILES = `${__dirname}\\svg`;
const JSON_MAP_FILES = `${__dirname}\\json`;
const EXPORTS_FILE = `${__dirname}\\index.js`;

class ConvertSVGs {
  async cleanAndCreateFolder(path) {
    await rimraf.sync(path);

    if (!fs.existsSync(path)) {
      fs.mkdirSync(path);
    }
  }

  async cleanAndCreateFile(path, data) {
    await rimraf.sync(path);

    if (!fs.existsSync(path)) {
      try {
        fs.writeFileSync(path, data);
      } catch (e) {
        throw e;
      }
    }
  }

  async run() {
    await this.cleanAndCreateFolder(JSON_MAP_FILES);

    const files = fs.readdirSync(SVG_MAP_FILES);

    const exports = [];
    const imports = [];

    await asyncForEach(files, async filename => {
      const path = `${SVG_MAP_FILES}\\${filename}`;
      const svg = fs.readFileSync(path, 'utf8');

      svgson.parse(svg).then(json => {
        const name = filename.split('.')[0];

        const layers = json.children
          .filter(({ name }) => name === 'path')
          .map(({ attributes }) => ({
            id: attributes.id.toLowerCase(),
            name: attributes.title || capitalize(attributes.id),
            d: attributes.d,
          }));

        const map = {
          id: name,
          name: capitalize(name.split('-').join(' ')),
          viewBox: `0 0 ${json.attributes.width} ${json.attributes.height}`,
          layers,
        };

        fs.writeFileSync(`${JSON_MAP_FILES}\\${name}.json`, stringify(map));
        1;

        const temp = capitalize(name.split('-').join(' '))
          .split(' ')
          .join('');
        const safeName = temp.charAt(0).toLowerCase() + temp.substr(1);

        imports.push(`import ${safeName} from './json/${name}.json';`);
        exports.push(`  ${safeName},`);
      });
    });

    await this.cleanAndCreateFile(
      EXPORTS_FILE,
      [
        '/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */',
        '',
        ...imports,
        '',
        'export {',
        ...exports,
        '};',
      ].join('\n'),
    );
  }
}

const convertSVGs = new ConvertSVGs();
convertSVGs.run();
