/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

import andorra from './json/andorra.json';
import angola from './json/angola.json';
import argentina from './json/argentina.json';
import armenia from './json/armenia.json';
import australia from './json/australia.json';
import austria from './json/austria.json';
import azerbaijan from './json/azerbaijan.json';
import bahamas from './json/bahamas.json';
import bahrain from './json/bahrain.json';
import bangladesh from './json/bangladesh.json';
import belarus from './json/belarus.json';
import belgium from './json/belgium.json';
import bhutan from './json/bhutan.json';
import bolivia from './json/bolivia.json';
import bosniaHerzegovina2 from './json/bosnia-herzegovina-2.json';
import bosniaHerzegovina from './json/bosnia-herzegovina.json';
import botswana from './json/botswana.json';
import brazil from './json/brazil.json';
import bruneiDarussalam from './json/brunei-darussalam.json';
import bulgaria from './json/bulgaria.json';
import burkinaFaso from './json/burkina-faso.json';
import burundi from './json/burundi.json';
import cambodia from './json/cambodia.json';
import cameroon from './json/cameroon.json';
import canada from './json/canada.json';
import capeVerde from './json/cape-verde.json';
import centralAfricanRepublic from './json/central-african-republic.json';
import chad from './json/chad.json';
import chile2 from './json/chile-2.json';
import chile from './json/chile.json';
import china from './json/china.json';
import colombia from './json/colombia.json';
import congoDr from './json/congo-dr.json';
import congo from './json/congo.json';
import costaRica from './json/costa-rica.json';
import croatia from './json/croatia.json';
import cuba from './json/cuba.json';
import cyprus from './json/cyprus.json';
import czechRepublic from './json/czech-republic.json';
import denmark from './json/denmark.json';
import djibouti from './json/djibouti.json';
import dominicanRepublic from './json/dominican-republic.json';
import ecuador from './json/ecuador.json';
import egypt from './json/egypt.json';
import elSalvador from './json/el-salvador.json';
import empty from './json/empty.json';
import estonia from './json/estonia.json';
import ethiopia from './json/ethiopia.json';
import faroeislands from './json/faroeIslands.json';
import finland from './json/finland.json';
import franceDepartments from './json/france-departments.json';
import franceNew from './json/france-new.json';
import france from './json/france.json';
import georgia from './json/georgia.json';
import germany from './json/germany.json';
import greece from './json/greece.json';
import guatemala from './json/guatemala.json';
import guinea from './json/guinea.json';
import haiti from './json/haiti.json';
import honduras from './json/honduras.json';
import hongKong from './json/hong-kong.json';
import hungary from './json/hungary.json';
import iceland from './json/iceland.json';
import india from './json/india.json';
import indonesia from './json/indonesia.json';
import iran from './json/iran.json';
import iraq from './json/iraq.json';
import ireland from './json/ireland.json';
import israel from './json/israel.json';
import italy from './json/italy.json';
import jamaica from './json/jamaica.json';
import japan from './json/japan.json';
import kazakhstan from './json/kazakhstan.json';
import kenya from './json/kenya.json';
import kosovo from './json/kosovo.json';
import kyrgyzstan from './json/kyrgyzstan.json';
import laos from './json/laos.json';
import latvia from './json/latvia.json';
import liechtenstein from './json/liechtenstein.json';
import lithuania from './json/lithuania.json';
import luxembourg from './json/luxembourg.json';
import macedonia from './json/macedonia.json';
import malaysia from './json/malaysia.json';
import mali from './json/mali.json';
import malta from './json/malta.json';
import mexico from './json/mexico.json';
import moldova from './json/moldova.json';
import montenegro from './json/montenegro.json';
import morocco from './json/morocco.json';
import myanmar from './json/myanmar.json';
import nepal from './json/nepal.json';
import netherlands from './json/netherlands.json';
import newZealand2 from './json/new-zealand-2.json';
import newZealand from './json/new-zealand.json';
import nicaragua from './json/nicaragua.json';
import nigeria from './json/nigeria.json';
import norway from './json/norway.json';
import oman from './json/oman.json';
import pakistan from './json/pakistan.json';
import palestine from './json/palestine.json';
import panama from './json/panama.json';
import paraguay from './json/paraguay.json';
import philippines from './json/philippines.json';
import poland from './json/poland.json';
import portugalRegions from './json/portugal-regions.json';
import portugal from './json/portugal.json';
import qatar from './json/qatar.json';
import romania from './json/romania.json';
import russia from './json/russia.json';
import rwanda from './json/rwanda.json';
import sanMarino from './json/san-marino.json';
import saudiArabia from './json/saudi-arabia.json';
import serbiaWithoutKosovo from './json/serbia-without-kosovo.json';
import serbia from './json/serbia.json';
import sierraLeone from './json/sierra-leone.json';
import singapore from './json/singapore.json';
import slovakia from './json/slovakia.json';
import slovenia from './json/slovenia.json';
import southAfrica2 from './json/south-africa-2.json';
import southAfrica from './json/south-africa.json';
import southKorea from './json/south-korea.json';
import spainProvinces from './json/spain-provinces.json';
import spain from './json/spain.json';
import sriLanka from './json/sri-lanka.json';
import sweden from './json/sweden.json';
import switzerland from './json/switzerland.json';
import syria from './json/syria.json';
import taiwan from './json/taiwan.json';
import tajikistan from './json/tajikistan.json';
import thailand from './json/thailand.json';
import turkey from './json/turkey.json';
import uganda from './json/uganda.json';
import ukraine from './json/ukraine.json';
import unitedArabEmirates from './json/united-arab-emirates.json';
import unitedKingdomCounties from './json/united-kingdom-counties.json';
import unitedKingdom from './json/united-kingdom.json';
import uruguay from './json/uruguay.json';
import usaAk from './json/usa-ak.json';
import usaAl from './json/usa-al.json';
import usaAr from './json/usa-ar.json';
import usaAz from './json/usa-az.json';
import usaCa from './json/usa-ca.json';
import usaCo from './json/usa-co.json';
import usaCt from './json/usa-ct.json';
import usaDe from './json/usa-de.json';
import usaFl from './json/usa-fl.json';
import usaGa from './json/usa-ga.json';
import usaHi from './json/usa-hi.json';
import usaIa from './json/usa-ia.json';
import usaId from './json/usa-id.json';
import usaIl from './json/usa-il.json';
import usaIn from './json/usa-in.json';
import usaKs from './json/usa-ks.json';
import usaKy from './json/usa-ky.json';
import usaLa from './json/usa-la.json';
import usaMa from './json/usa-ma.json';
import usaMd from './json/usa-md.json';
import usaMe from './json/usa-me.json';
import usaMi from './json/usa-mi.json';
import usaMn from './json/usa-mn.json';
import usaMo from './json/usa-mo.json';
import usaMs from './json/usa-ms.json';
import usaMt from './json/usa-mt.json';
import usaNc from './json/usa-nc.json';
import usaNd from './json/usa-nd.json';
import usaNe from './json/usa-ne.json';
import usaNh from './json/usa-nh.json';
import usaNj from './json/usa-nj.json';
import usaNm from './json/usa-nm.json';
import usaNotCalibrated from './json/usa-not-calibrated.json';
import usaNv from './json/usa-nv.json';
import usaNy from './json/usa-ny.json';
import usaOh from './json/usa-oh.json';
import usaOk from './json/usa-ok.json';
import usaOr from './json/usa-or.json';
import usaPa from './json/usa-pa.json';
import usaRi from './json/usa-ri.json';
import usaSc from './json/usa-sc.json';
import usaSd from './json/usa-sd.json';
import usaTn from './json/usa-tn.json';
import usaTx from './json/usa-tx.json';
import usaUt from './json/usa-ut.json';
import usaVa from './json/usa-va.json';
import usaVt from './json/usa-vt.json';
import usaWa from './json/usa-wa.json';
import usaWdc from './json/usa-wdc.json';
import usaWi from './json/usa-wi.json';
import usaWithAkHi from './json/usa-with-AK-HI.json';
import usaWv from './json/usa-wv.json';
import usaWy from './json/usa-wy.json';
import usa from './json/usa.json';
import uzbekistan from './json/uzbekistan.json';
import venezuela from './json/venezuela.json';
import vietnamWithIslands from './json/vietnam-with-islands.json';
import vietnam from './json/vietnam.json';
import worldLowRes from './json/world-low-res.json';
import world from './json/world.json';

export {
  andorra,
  angola,
  argentina,
  armenia,
  australia,
  austria,
  azerbaijan,
  bahamas,
  bahrain,
  bangladesh,
  belarus,
  belgium,
  bhutan,
  bolivia,
  bosniaHerzegovina2,
  bosniaHerzegovina,
  botswana,
  brazil,
  bruneiDarussalam,
  bulgaria,
  burkinaFaso,
  burundi,
  cambodia,
  cameroon,
  canada,
  capeVerde,
  centralAfricanRepublic,
  chad,
  chile2,
  chile,
  china,
  colombia,
  congoDr,
  congo,
  costaRica,
  croatia,
  cuba,
  cyprus,
  czechRepublic,
  denmark,
  djibouti,
  dominicanRepublic,
  ecuador,
  egypt,
  elSalvador,
  empty,
  estonia,
  ethiopia,
  faroeislands,
  finland,
  franceDepartments,
  franceNew,
  france,
  georgia,
  germany,
  greece,
  guatemala,
  guinea,
  haiti,
  honduras,
  hongKong,
  hungary,
  iceland,
  india,
  indonesia,
  iran,
  iraq,
  ireland,
  israel,
  italy,
  jamaica,
  japan,
  kazakhstan,
  kenya,
  kosovo,
  kyrgyzstan,
  laos,
  latvia,
  liechtenstein,
  lithuania,
  luxembourg,
  macedonia,
  malaysia,
  mali,
  malta,
  mexico,
  moldova,
  montenegro,
  morocco,
  myanmar,
  nepal,
  netherlands,
  newZealand2,
  newZealand,
  nicaragua,
  nigeria,
  norway,
  oman,
  pakistan,
  palestine,
  panama,
  paraguay,
  philippines,
  poland,
  portugalRegions,
  portugal,
  qatar,
  romania,
  russia,
  rwanda,
  sanMarino,
  saudiArabia,
  serbiaWithoutKosovo,
  serbia,
  sierraLeone,
  singapore,
  slovakia,
  slovenia,
  southAfrica2,
  southAfrica,
  southKorea,
  spainProvinces,
  spain,
  sriLanka,
  sweden,
  switzerland,
  syria,
  taiwan,
  tajikistan,
  thailand,
  turkey,
  uganda,
  ukraine,
  unitedArabEmirates,
  unitedKingdomCounties,
  unitedKingdom,
  uruguay,
  usaAk,
  usaAl,
  usaAr,
  usaAz,
  usaCa,
  usaCo,
  usaCt,
  usaDe,
  usaFl,
  usaGa,
  usaHi,
  usaIa,
  usaId,
  usaIl,
  usaIn,
  usaKs,
  usaKy,
  usaLa,
  usaMa,
  usaMd,
  usaMe,
  usaMi,
  usaMn,
  usaMo,
  usaMs,
  usaMt,
  usaNc,
  usaNd,
  usaNe,
  usaNh,
  usaNj,
  usaNm,
  usaNotCalibrated,
  usaNv,
  usaNy,
  usaOh,
  usaOk,
  usaOr,
  usaPa,
  usaRi,
  usaSc,
  usaSd,
  usaTn,
  usaTx,
  usaUt,
  usaVa,
  usaVt,
  usaWa,
  usaWdc,
  usaWi,
  usaWithAkHi,
  usaWv,
  usaWy,
  usa,
  uzbekistan,
  venezuela,
  vietnamWithIslands,
  vietnam,
  worldLowRes,
  world,
};
